# port: 4466
# managementApiSecret: ${env:PRISMA_MANAGEMENT_API_SECRET}
# databases:
#   default:
#     connector: mysql
#     host: dokku-mysql-florestaprotegida-db
#     name: florestaprotegida_db
#     port: 3306
#     user: mysql
#     password: ${env:DATABASE_PASSWORD}
#     migrations: true

port: 4466
databases:
  default:
    connector: postgres
    host: dokku-postgres-prisma-server-db
    port: 5432
    user: postgres
    password: 8e148681e2a980fb93a5fdb781882d1d
    migrations: true
