port: 4466
databases:
  default:
    connector: mysql
    host: dokku-mysql-florestaprotegida-db
    port: 3306
    user: florestaprotegida_db
    password: ${env:DATABASE_PASSWORD}
    migrations: true