# port: 4466
# managementApiSecret: ${env:}
# databases:
#   default:
#     connector: mysql
#     host: dokku-mysql-florestaprotegida-db
#     name: florestaprotegida_db
#     port: 3306
#     user: mysql
#     password: ${env:DATABASE_PASSWORD}
#     migrations: true

# port: 4466
# databases:
#   default:
#     connector: postgres
#     host: dokku-postgres-prisma-server-db
#     port: 5432
#     user: postgres
#     password: 8e148681e2a980fb93a5fdb781882d1d
#     migrations: true

managementApiSecret: PRISMA_MANAGEMENT_API_SECRET
port: 4466
databases:
    default:
        connector: mysql
        host: dokku-mysql-florestaprotegida-db
        port: 3306
        user: mysql
        password: DATABASE_PASSWORD
        migrations: true
        active: true