version: '2'
services:
  minio:
    image: minio/minio
    volumes:
      - 'data1:/data'
    ports:
      - '9000:9000'
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
volumes:
  data1: null
